version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5.2-browsers
      - image: circleci/postgres:9.5-alpine
        env:
          - POSTGRES_USER=root
    working_directory: ~/phoenix_intercooler_tutorial
    steps:
      - checkout
      - run:
          command: chromedriver
          background: true
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix espec --exclude feature
      - run: mix espec --only feature
      - run: mix coveralls.circle
      - run: mix inch.report
      - store_artifacts:
          path: screenshots
          destination: screenshots
